/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFieldMetadataEntry {
    /// Lance field path whose metadata to update. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments. Use canonical full paths for display and errors; leaf names alone only identify top-level fields; invalid or unresolved paths should return InvalidInput or TableColumnNotFound.
    #[serde(rename = "path")]
    pub path: String,
    /// Metadata key-value pairs to apply to the field. A null value deletes that key. 
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, String>,
    /// If true, replace the field's existing metadata entirely; otherwise merge into it (optional, defaults to false). 
    #[serde(rename = "replace", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub replace: Option<Option<bool>>,
}

impl UpdateFieldMetadataEntry {
    pub fn new(path: String, metadata: std::collections::HashMap<String, String>) -> UpdateFieldMetadataEntry {
        UpdateFieldMetadataEntry {
            path,
            metadata,
            replace: None,
        }
    }
}

