# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.list_table_indices_response import ListTableIndicesResponse

class TestListTableIndicesResponse(unittest.TestCase):
    """ListTableIndicesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTableIndicesResponse:
        """Test ListTableIndicesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTableIndicesResponse`
        """
        model = ListTableIndicesResponse()
        if include_optional:
            return ListTableIndicesResponse(
                indexes = [
                    lance_namespace_urllib3_client.models.index_content.IndexContent(
                        index_name = '', 
                        index_uuid = '', 
                        columns = [
                            ''
                            ], 
                        status = '', 
                        index_type = '', 
                        type_url = '', 
                        num_indexed_rows = 0, 
                        num_unindexed_rows = 0, 
                        size_bytes = 0, 
                        num_segments = 0, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        index_version = 0, 
                        index_details = '', )
                    ],
                page_token = ''
            )
        else:
            return ListTableIndicesResponse(
                indexes = [
                    lance_namespace_urllib3_client.models.index_content.IndexContent(
                        index_name = '', 
                        index_uuid = '', 
                        columns = [
                            ''
                            ], 
                        status = '', 
                        index_type = '', 
                        type_url = '', 
                        num_indexed_rows = 0, 
                        num_unindexed_rows = 0, 
                        size_bytes = 0, 
                        num_segments = 0, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        index_version = 0, 
                        index_details = '', )
                    ],
        )
        """

    def testListTableIndicesResponse(self):
        """Test ListTableIndicesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
