# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.merge_insert_into_table_request import MergeInsertIntoTableRequest

class TestMergeInsertIntoTableRequest(unittest.TestCase):
    """MergeInsertIntoTableRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MergeInsertIntoTableRequest:
        """Test MergeInsertIntoTableRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MergeInsertIntoTableRequest`
        """
        model = MergeInsertIntoTableRequest()
        if include_optional:
            return MergeInsertIntoTableRequest(
                identity = lance_namespace_urllib3_client.models.identity.Identity(
                    api_key = '', 
                    auth_token = '', ),
                context = {
                    'key' : ''
                    },
                id = [
                    ''
                    ],
                branch = '',
                on = '0',
                when_matched_update_all = True,
                when_matched_update_all_filt = '',
                when_not_matched_insert_all = True,
                when_not_matched_by_source_delete = True,
                when_not_matched_by_source_delete_filt = '',
                timeout = '',
                use_index = True
            )
        else:
            return MergeInsertIntoTableRequest(
        )
        """

    def testMergeInsertIntoTableRequest(self):
        """Test MergeInsertIntoTableRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
