# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.alter_table_alter_columns_request import AlterTableAlterColumnsRequest

class TestAlterTableAlterColumnsRequest(unittest.TestCase):
    """AlterTableAlterColumnsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlterTableAlterColumnsRequest:
        """Test AlterTableAlterColumnsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlterTableAlterColumnsRequest`
        """
        model = AlterTableAlterColumnsRequest()
        if include_optional:
            return AlterTableAlterColumnsRequest(
                identity = lance_namespace_urllib3_client.models.identity.Identity(
                    api_key = '', 
                    auth_token = '', ),
                id = [
                    ''
                    ],
                branch = '',
                alterations = [
                    lance_namespace_urllib3_client.models.alter_columns_entry.AlterColumnsEntry(
                        path = '0', 
                        data_type = lance_namespace_urllib3_client.models.data_type.data_type(), 
                        rename = '', 
                        nullable = True, 
                        virtual_column = lance_namespace_urllib3_client.models.alter_virtual_column_entry.AlterVirtualColumnEntry(
                            input_columns = [
                                '0'
                                ], 
                            image = '', 
                            udf = '', 
                            udf_name = '', 
                            udf_version = '', 
                            udf_backend = '', 
                            auto_backfill = True, 
                            manifest = '', 
                            manifest_checksum = '', 
                            field_metadata = {
                                'key' : ''
                                }, ), )
                    ]
            )
        else:
            return AlterTableAlterColumnsRequest(
                alterations = [
                    lance_namespace_urllib3_client.models.alter_columns_entry.AlterColumnsEntry(
                        path = '0', 
                        data_type = lance_namespace_urllib3_client.models.data_type.data_type(), 
                        rename = '', 
                        nullable = True, 
                        virtual_column = lance_namespace_urllib3_client.models.alter_virtual_column_entry.AlterVirtualColumnEntry(
                            input_columns = [
                                '0'
                                ], 
                            image = '', 
                            udf = '', 
                            udf_name = '', 
                            udf_version = '', 
                            udf_backend = '', 
                            auto_backfill = True, 
                            manifest = '', 
                            manifest_checksum = '', 
                            field_metadata = {
                                'key' : ''
                                }, ), )
                    ],
        )
        """

    def testAlterTableAlterColumnsRequest(self):
        """Test AlterTableAlterColumnsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
