# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.alter_table_backfill_columns_request import AlterTableBackfillColumnsRequest

class TestAlterTableBackfillColumnsRequest(unittest.TestCase):
    """AlterTableBackfillColumnsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlterTableBackfillColumnsRequest:
        """Test AlterTableBackfillColumnsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlterTableBackfillColumnsRequest`
        """
        model = AlterTableBackfillColumnsRequest()
        if include_optional:
            return AlterTableBackfillColumnsRequest(
                identity = lance_namespace_urllib3_client.models.identity.Identity(
                    api_key = '', 
                    auth_token = '', ),
                id = [
                    ''
                    ],
                branch = '',
                column = '0',
                where = '',
                concurrency = 56,
                intra_applier_concurrency = 56,
                min_checkpoint_size = 56,
                max_checkpoint_size = 56,
                batch_checkpoint_flush_interval_seconds = 1.337,
                read_version = 56,
                task_size = 56,
                num_frags = 56,
                checkpoint_size = 56,
                commit_granularity = 56,
                cluster = '',
                manifest = ''
            )
        else:
            return AlterTableBackfillColumnsRequest(
                column = '0',
        )
        """

    def testAlterTableBackfillColumnsRequest(self):
        """Test AlterTableBackfillColumnsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
