# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.materialized_view_udtf_entry import MaterializedViewUdtfEntry

class TestMaterializedViewUdtfEntry(unittest.TestCase):
    """MaterializedViewUdtfEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaterializedViewUdtfEntry:
        """Test MaterializedViewUdtfEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaterializedViewUdtfEntry`
        """
        model = MaterializedViewUdtfEntry()
        if include_optional:
            return MaterializedViewUdtfEntry(
                kind = 'udtf',
                udtf = '',
                udtf_sha = '',
                udtf_name = '',
                udtf_version = '',
                input_columns = [
                    '0'
                    ],
                partition_by = '0',
                partition_by_indexed_column = '0',
                num_cpus = 1.337,
                num_gpus = 1.337,
                memory = 56,
                error_handling = lance_namespace_urllib3_client.models.error_handling.error_handling(),
                batch = True,
                manifest = '',
                manifest_checksum = ''
            )
        else:
            return MaterializedViewUdtfEntry(
                kind = 'udtf',
                udtf = '',
                udtf_sha = '',
                udtf_name = '',
                udtf_version = '',
        )
        """

    def testMaterializedViewUdtfEntry(self):
        """Test MaterializedViewUdtfEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
