# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lance_namespace_urllib3_client.models.add_virtual_column_output_entry import AddVirtualColumnOutputEntry
from typing import Optional, Set
from typing_extensions import Self

class AddVirtualColumnEntry(BaseModel):
    """
    AddVirtualColumnEntry
    """ # noqa: E501
    input_columns: List[Annotated[str, Field(min_length=1, strict=True)]] = Field(description="List of input Lance field paths for the virtual column. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments.")
    outputs: List[AddVirtualColumnOutputEntry] = Field(description="Output columns produced by the virtual column UDF")
    image: StrictStr = Field(description="Docker image to use for the UDF")
    udf: StrictStr = Field(description="Base64 encoded pickled UDF")
    udf_name: StrictStr = Field(description="Name of the UDF")
    udf_version: StrictStr = Field(description="Version of the UDF")
    udf_backend: Optional[StrictStr] = Field(default=None, description="UDF backend type (e.g. DockerUDFSpecV1)")
    auto_backfill: Optional[StrictBool] = Field(default=None, description="Whether to automatically backfill the column after creation")
    manifest: Optional[StrictStr] = Field(default=None, description="JSON-serialized manifest for the UDF environment")
    manifest_checksum: Optional[StrictStr] = Field(default=None, description="SHA-256 checksum of the manifest content")
    field_metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="User-supplied field metadata (string key-value pairs)")
    __properties: ClassVar[List[str]] = ["input_columns", "outputs", "image", "udf", "udf_name", "udf_version", "udf_backend", "auto_backfill", "manifest", "manifest_checksum", "field_metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddVirtualColumnEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                if _item_outputs:
                    _items.append(_item_outputs.to_dict())
            _dict['outputs'] = _items
        # set to None if udf_backend (nullable) is None
        # and model_fields_set contains the field
        if self.udf_backend is None and "udf_backend" in self.model_fields_set:
            _dict['udf_backend'] = None

        # set to None if auto_backfill (nullable) is None
        # and model_fields_set contains the field
        if self.auto_backfill is None and "auto_backfill" in self.model_fields_set:
            _dict['auto_backfill'] = None

        # set to None if manifest (nullable) is None
        # and model_fields_set contains the field
        if self.manifest is None and "manifest" in self.model_fields_set:
            _dict['manifest'] = None

        # set to None if manifest_checksum (nullable) is None
        # and model_fields_set contains the field
        if self.manifest_checksum is None and "manifest_checksum" in self.model_fields_set:
            _dict['manifest_checksum'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddVirtualColumnEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "input_columns": obj.get("input_columns"),
            "outputs": [AddVirtualColumnOutputEntry.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "image": obj.get("image"),
            "udf": obj.get("udf"),
            "udf_name": obj.get("udf_name"),
            "udf_version": obj.get("udf_version"),
            "udf_backend": obj.get("udf_backend"),
            "auto_backfill": obj.get("auto_backfill"),
            "manifest": obj.get("manifest"),
            "manifest_checksum": obj.get("manifest_checksum"),
            "field_metadata": obj.get("field_metadata")
        })
        return _obj


