# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lance_namespace_urllib3_client.models.alter_virtual_column_entry import AlterVirtualColumnEntry
from typing import Optional, Set
from typing_extensions import Self

class AlterColumnsEntry(BaseModel):
    """
    AlterColumnsEntry
    """ # noqa: E501
    path: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Lance field path to alter. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments. Use canonical full paths for display and errors; leaf names alone only identify top-level fields; invalid or unresolved paths should return InvalidInput or TableColumnNotFound.")
    data_type: Optional[Dict[str, Any]] = Field(default=None, description="New data type for the column using JSON representation (optional)")
    rename: Optional[StrictStr] = Field(default=None, description="New name for the column (optional)")
    nullable: Optional[StrictBool] = Field(default=None, description="Whether the column should be nullable (optional)")
    virtual_column: Optional[AlterVirtualColumnEntry] = None
    __properties: ClassVar[List[str]] = ["path", "data_type", "rename", "nullable", "virtual_column"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlterColumnsEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of virtual_column
        if self.virtual_column:
            _dict['virtual_column'] = self.virtual_column.to_dict()
        # set to None if rename (nullable) is None
        # and model_fields_set contains the field
        if self.rename is None and "rename" in self.model_fields_set:
            _dict['rename'] = None

        # set to None if nullable (nullable) is None
        # and model_fields_set contains the field
        if self.nullable is None and "nullable" in self.model_fields_set:
            _dict['nullable'] = None

        # set to None if virtual_column (nullable) is None
        # and model_fields_set contains the field
        if self.virtual_column is None and "virtual_column" in self.model_fields_set:
            _dict['virtual_column'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlterColumnsEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "data_type": obj.get("data_type"),
            "rename": obj.get("rename"),
            "nullable": obj.get("nullable"),
            "virtual_column": AlterVirtualColumnEntry.from_dict(obj["virtual_column"]) if obj.get("virtual_column") is not None else None
        })
        return _obj


