# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class IndexContent(BaseModel):
    """
    IndexContent
    """ # noqa: E501
    index_name: StrictStr = Field(description="Name of the index")
    index_uuid: StrictStr = Field(description="Unique identifier for the index")
    columns: List[Annotated[str, Field(min_length=1, strict=True)]] = Field(description="Canonical Lance field paths covered by this index. Nested fields use dot-separated segments; segments containing literal dots are backtick-quoted, and backticks inside quoted segments are doubled.")
    status: StrictStr = Field(description="Current status of the index")
    index_type: Optional[StrictStr] = Field(default=None, description="Friendly index type, e.g. IVF_PQ, BTREE. Unknown if no plugin recognizes the index.")
    type_url: Optional[StrictStr] = Field(default=None, description="Protobuf type URL, a precise type identifier for the index.")
    num_indexed_rows: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Number of live rows covered by the index. This does not count rows that are in the index but have since been deleted.")
    num_unindexed_rows: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Number of rows that are not indexed.")
    size_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total index size in bytes across all segments. Null for indices predating file-size tracking.")
    num_segments: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Number of index deltas/segments.")
    created_at: Optional[datetime] = Field(default=None, description="Creation time for indexes. Null for legacy indices.")
    index_version: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="On-disk index format version.")
    index_details: Optional[StrictStr] = Field(default=None, description="Opaque, type-specific JSON with additional index details. For vector indices this carries metric/distance type, partitioning, and HNSW/PQ/SQ/RQ parameters.")
    __properties: ClassVar[List[str]] = ["index_name", "index_uuid", "columns", "status", "index_type", "type_url", "num_indexed_rows", "num_unindexed_rows", "size_bytes", "num_segments", "created_at", "index_version", "index_details"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndexContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndexContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index_name": obj.get("index_name"),
            "index_uuid": obj.get("index_uuid"),
            "columns": obj.get("columns"),
            "status": obj.get("status"),
            "index_type": obj.get("index_type"),
            "type_url": obj.get("type_url"),
            "num_indexed_rows": obj.get("num_indexed_rows"),
            "num_unindexed_rows": obj.get("num_unindexed_rows"),
            "size_bytes": obj.get("size_bytes"),
            "num_segments": obj.get("num_segments"),
            "created_at": obj.get("created_at"),
            "index_version": obj.get("index_version"),
            "index_details": obj.get("index_details")
        })
        return _obj


