# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class MaterializedViewUdtfEntry(BaseModel):
    """
    MaterializedViewUdtfEntry
    """ # noqa: E501
    kind: StrictStr = Field(description="Discriminates a batch UDTF (`udtf`, full-overwrite refresh) from a chunker (`chunker`, incremental 1:N refresh). Must match the enclosing request's `kind`. ")
    udtf: StrictStr = Field(description="Base64-encoded UDTFSpec / ChunkerSpec JSON envelope (per kind). ")
    udtf_sha: StrictStr = Field(description="SHA-256 checksum of the envelope; server validates.")
    udtf_name: StrictStr = Field(description="Name of the UDTF")
    udtf_version: StrictStr = Field(description="Version of the UDTF")
    input_columns: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = Field(default=None, description="Source Lance field paths the UDTF reads. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments. Null means all fields (batch UDTF only). ")
    partition_by: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    partition_by_indexed_column: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    num_cpus: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Ray actor CPU request.")
    num_gpus: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Ray actor GPU request.")
    memory: Optional[StrictInt] = Field(default=None, description="Ray actor memory request, in bytes.")
    error_handling: Optional[Dict[str, Any]] = Field(default=None, description="Batch UDTF only. Serialized ErrorHandlingConfig controlling partition-grain fail/retry/skip behavior. ")
    batch: Optional[StrictBool] = Field(default=None, description="Chunker only. True for a batched chunker; affects how the worker dispatches input rows. ")
    manifest: Optional[StrictStr] = Field(default=None, description="JSON-serialized GenevaManifest for the UDTF environment.")
    manifest_checksum: Optional[StrictStr] = Field(default=None, description="SHA-256 checksum of the manifest content.")
    __properties: ClassVar[List[str]] = ["kind", "udtf", "udtf_sha", "udtf_name", "udtf_version", "input_columns", "partition_by", "partition_by_indexed_column", "num_cpus", "num_gpus", "memory", "error_handling", "batch", "manifest", "manifest_checksum"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['udtf', 'chunker']):
            raise ValueError("must be one of enum values ('udtf', 'chunker')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MaterializedViewUdtfEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if input_columns (nullable) is None
        # and model_fields_set contains the field
        if self.input_columns is None and "input_columns" in self.model_fields_set:
            _dict['input_columns'] = None

        # set to None if partition_by (nullable) is None
        # and model_fields_set contains the field
        if self.partition_by is None and "partition_by" in self.model_fields_set:
            _dict['partition_by'] = None

        # set to None if partition_by_indexed_column (nullable) is None
        # and model_fields_set contains the field
        if self.partition_by_indexed_column is None and "partition_by_indexed_column" in self.model_fields_set:
            _dict['partition_by_indexed_column'] = None

        # set to None if num_cpus (nullable) is None
        # and model_fields_set contains the field
        if self.num_cpus is None and "num_cpus" in self.model_fields_set:
            _dict['num_cpus'] = None

        # set to None if num_gpus (nullable) is None
        # and model_fields_set contains the field
        if self.num_gpus is None and "num_gpus" in self.model_fields_set:
            _dict['num_gpus'] = None

        # set to None if memory (nullable) is None
        # and model_fields_set contains the field
        if self.memory is None and "memory" in self.model_fields_set:
            _dict['memory'] = None

        # set to None if error_handling (nullable) is None
        # and model_fields_set contains the field
        if self.error_handling is None and "error_handling" in self.model_fields_set:
            _dict['error_handling'] = None

        # set to None if batch (nullable) is None
        # and model_fields_set contains the field
        if self.batch is None and "batch" in self.model_fields_set:
            _dict['batch'] = None

        # set to None if manifest (nullable) is None
        # and model_fields_set contains the field
        if self.manifest is None and "manifest" in self.model_fields_set:
            _dict['manifest'] = None

        # set to None if manifest_checksum (nullable) is None
        # and model_fields_set contains the field
        if self.manifest_checksum is None and "manifest_checksum" in self.model_fields_set:
            _dict['manifest_checksum'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MaterializedViewUdtfEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "udtf": obj.get("udtf"),
            "udtf_sha": obj.get("udtf_sha"),
            "udtf_name": obj.get("udtf_name"),
            "udtf_version": obj.get("udtf_version"),
            "input_columns": obj.get("input_columns"),
            "partition_by": obj.get("partition_by"),
            "partition_by_indexed_column": obj.get("partition_by_indexed_column"),
            "num_cpus": obj.get("num_cpus"),
            "num_gpus": obj.get("num_gpus"),
            "memory": obj.get("memory"),
            "error_handling": obj.get("error_handling"),
            "batch": obj.get("batch"),
            "manifest": obj.get("manifest"),
            "manifest_checksum": obj.get("manifest_checksum")
        })
        return _obj


